In [3]:
import numpy as np

nilai = np.array([[80, 75, 90, 88], [70, 60, 85, 78], [95, 88, 92, 96]])
ratarata = nilai.mean(axis=1)
tertinggi = nilai.max()
tiga = nilai [:,2]
ratatinggi = ratarata.max()

print(f"nilai :\n{nilai}\nRata-rata nilai setiap siswa: {rataarata}\nNilai tertinggi: {tertinggi}\nNilai ketiga setiap siswa: {tiga}\nRata-rata tertinggi: {ratatinggi}")

nilai :
[[80 75 90 88]
 [70 60 85 78]
 [95 88 92 96]]
Rata-rata nilai setiap siswa: [83.25 73.25 92.75]
Nilai tertinggi: 96
Nilai ketiga setiap siswa: [90 85 92]
Rata-rata tertinggi: 92.75


In [2]:
pip install pandas

   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.0 MB 7.4 MB/s eta 0:00:02
   ------- -------------------------------- 2.1/11.0 MB 5.9 MB/s eta 0:00:02
   --------- ------------------------------ 2.6/11.0 MB 5.0 MB/s eta 0:00:02
   ------------- -------------------------- 3.7/11.0 MB 4.6 MB/s eta 0:00:02
   ----------------- ---------------------- 4.7/11.0 MB 4.8 MB/s eta 0:00:02
   --------------------- ------------------ 6.0/11.0 MB 5.0 MB/s eta 0:00:01
   ------------------------ --------------- 6.8/11.0 MB 4.8 MB/s eta 0:00:01
   ----------------------------- ---------- 8.1/11.0 MB 5.0 MB/s eta 0:00:01
   ----------------------------------- ---- 9.7/11.0 MB 5.2 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/11.0 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 4.7 MB/s  0:00:02

   --


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip
